# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dff3773eecace3f39f8e46acd4efea41da59ab0ce2f6c64a53568e607e18dec5effe35a4efa536a104f0d5d885270a2b62dd3e72d74e0fc7bbb0a896eae039af

test:
  secret_key_base: d9e98b5a3f70db6bf426300e84566f3f4b2fe2dfe46ff7111432f41788a75a063ad2a3349dcf62e51284abbc7ca64e4c564319f90be035d724a4c4fb3404d6bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
